### ISSUE TITLE
singlefile-updates/version-1-22 SingleFileZ GH URL points to SingleFile

### ISSUE THREAD

**Issue by myfonj** [gildas-lormeau/gildas-lormeau.github.io#2]
https://github.com/gildas-lormeau/gildas-lormeau.github.io/blob/e6b60ac9926e8a7fef9b470ab1b36c1dd2e25d19/singlefile-updates/version-1-22.html#L96-L97

Btw, does it mean that SingleFileZ is effectively merged and development will continue in SingleFile? This info would maybe also worth adding into version notes (and SingleFileZ readme).

**Comment by gildas-lormeau** [comment]
Thank you, I fixed the link. Regarding SingleFileZ, it will indeed retire after years of loyal service. For the time being, I'll continue to maintain it, and if all goes well, I'll make an announcement in SingleFileZ.

**Comment by myfonj** [comment]
Fixed by 3b09917.
